### ISSUE TITLE
pairing on a vps?

### ISSUE THREAD

**Issue by DumbGameMaker** [jkcoxson/netmuxd#15]
I have a vps on which I host my own vpn. I was hoping to be able to put altserver on that vps so i could use it when not at home. Is there a way to pair my device with the vps, without a usb connection?

**Comment by jkcoxson** [comment]
There are a number of problems with this
1. The only way iOS will accept a pairing file is over USB. lockdownd will reject a pairing request otherwise.
2. AltStore will not work over a VPN. It requires mDNS going both ways, and netmuxd only fixes it going server -> VPS, not the other way. There is a project that called [SideStore](https://github.com/SideStore) that I am a part of that is working to solve this issue through a fork of AltStore, but is not ready for production use.

**Comment by DumbGameMaker** [comment]
ah ok, ty

**Comment by DumbGameMaker** [comment]
@jkcoxson is sidestore server compatible with the altstore app? or do i have to install sidestore's app?

**Comment by jkcoxson** [comment]
Once SideStore is complete, it will replace AltStore’s app. We are not there yet, it will be a bit before it’s usable for end users.
